services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.17.0'
    volumes:
      - poc_elasticsearch:/usr/share/elasticsearch/data
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    mem_limit: 2147483648
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'cluster_name'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

    ports:
      - 9200:9200
      - '9300'
  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: 'docker.elastic.co/kibana/kibana:8.17.0'
    volumes:
      - poc_kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    mem_limit: 1073741824
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'

volumes:
  poc_elasticsearch:
    driver: local
  poc_kibanadata:
    driver: local

